version: "3.8"
services:
  mongo:
    image: mongo:6.0.3
    command: "--setParameter allowDiskUseByDefault=true"
    restart: always
    expose:
      - 27017

  ipfs-node:
    image: ipfs/kubo:v0.17.0
    ports:
      - "5001:5001"
      - "5002:5002"
      - "4001:4001"
      - "4002:4002"
      - "8080:8080"
      - "8081:8081"

  api-docs:
    image: gcr.io/hedera-registry/api-docs
    restart: always
    expose:
      - 3001

  message-broker:
    image: nats:2.9.8
    expose:
      - 4222
    ports:
      - '8222:8222'
    command: '--http_port 8222'

  vault:
    image: vault:1.12.2
    expose:
      - 8200
    ports:
      - '8200:8200'
    environment:
      VAULT_SERVER: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "1234"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw

  logger-service:
    image: gcr.io/hedera-registry/logger-service
    restart: always
    depends_on:
      - message-broker

  worker-service-1:
    image: gcr.io/hedera-registry/worker-service
    restart: always
    depends_on:
      - ipfs-node
      - auth-service
    environment:
      - SERVICE_CHANNEL="worker.1"
      - IPFS_PROVIDER="web3storage"
      - IPFS_STORAGE_API_KEY=""

  worker-service-2:
    image: gcr.io/hedera-registry/worker-service
    restart: always
    depends_on:
      - ipfs-node
      - auth-service
    environment:
      - SERVICE_CHANNEL="worker.2"
      - IPFS_PROVIDER="web3storage"
      - IPFS_STORAGE_API_KEY=""

  auth-service:
    image: gcr.io/hedera-registry/auth-service
    restart: always
    depends_on:
      - mongo
      - vault
      - message-broker
      - logger-service

  api-gateway:
    image: gcr.io/hedera-registry/api-gateway
    restart: always
    expose:
      - 3002
    depends_on:
      - mongo
      - message-broker
      - guardian-service
      - auth-service
      - logger-service

  guardian-service:
    image: gcr.io/hedera-registry/guardian-service
    restart: always
    depends_on:
      - mongo
      - message-broker
      - auth-service
      - logger-service
      - worker-service-1
      - worker-service-2
    environment:
      - OPERATOR_ID=""
      - OPERATOR_KEY=""

  mrv-sender:
    image: gcr.io/hedera-registry/mrv-sender
    restart: always
    expose:
      - 3005

  topic-viewer:
    image: gcr.io/hedera-registry/topic-viewer
    restart: always
    expose:
      - 3006

  web-proxy:
    build:
      context: .
      dockerfile: ./web-proxy/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - guardian-service
      - auth-service
      - api-gateway
      - api-docs
      - mrv-sender
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge

volumes:
  mongo:
    # volume-guardian-service:
    # volume-ui-service:
    # volume-mrv-sender:
    #  volume-message-broker:
    